import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { Screen, Topbar, BtnPrimary, BtnOutline, Chip, Avatar, Divider } from '../components.jsx'
import { DEFAULT_PRODUCTION, WORKSTREAMS, MILESTONES, DAY1_ACTIONS } from '../data.js'

export default function ProductionBrief({ onLaunch, onBack, inWorkspace }) {
  const p = DEFAULT_PRODUCTION

  const content = (
    <div style={{ maxWidth: 820, margin: '0 auto', padding: inWorkspace ? '32px 40px 80px' : '0 40px 100px' }}>
      {/* Hero header */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.25,1,0.5,1] }}
        style={{ padding: inWorkspace ? '0 0 36px' : '44px 0 36px', borderBottom: '1px solid var(--border)', marginBottom: 40 }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 40 }}>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 16 }}>
              <Chip color="neutral">{p.type}</Chip>
              <Chip color="neutral">{p.venue}</Chip>
              <Chip color="neutral">{p.guestCount}</Chip>
              <Chip color="blue">Generated by Fieldwork</Chip>
            </div>
            <h1 style={{ fontSize: 34, fontWeight: 400, letterSpacing: '-0.03em', lineHeight: 1.08, marginBottom: 16, color: 'var(--ink-900)' }}>
              {p.name}
            </h1>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
              <MetaRow label="Client" value={p.client} />
              <MetaRow label="Executive Producer" value={p.ep} />
              <MetaRow label="Lead Producer" value={p.lead} />
              <MetaRow label="Budget envelope" value={p.budgetRange + ' · ' + p.budgetTier + ' scale'} />
            </div>
          </div>
          <div style={{ flexShrink: 0, textAlign: 'right', paddingTop: 4, borderLeft: '1px solid var(--border)', paddingLeft: 36 }}>
            <p style={{ fontSize: 72, fontWeight: 300, letterSpacing: '-0.05em', lineHeight: 1, fontFamily: 'var(--font-display)', color: 'var(--ink-900)' }}>
              {p.daysOut}
            </p>
            <p style={{ fontSize: 11, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--ink-400)', marginTop: 6, fontWeight: 500 }}>Days to event</p>
            <div style={{ marginTop: 14, paddingTop: 14, borderTop: '1px solid var(--border)' }}>
              <p style={{ fontSize: 15, fontWeight: 500, color: 'var(--ink-900)' }}>{p.eventDate}</p>
              <p style={{ fontSize: 12, color: 'var(--ink-400)', marginTop: 2 }}>Brooklyn Tower · {p.location}</p>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Schedule */}
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, delay: 0.06, ease: [0.25,1,0.5,1] }} style={{ marginBottom: 40 }}>
        <SectionHeader label="Production schedule" note="Dates calculated backward from event day" />
        <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: '28px 32px 24px' }}>
          <MilestoneTimeline milestones={MILESTONES} />
        </div>
      </motion.div>

      {/* Workstreams */}
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, delay: 0.1, ease: [0.25,1,0.5,1] }} style={{ marginBottom: 40 }}>
        <SectionHeader label="Workstreams & department leads" note="6 workstreams · 37 tasks auto-assigned at launch" />
        <div style={{ display: 'flex', flexDirection: 'column', gap: 1, border: '1px solid var(--border)', borderRadius: 'var(--r-md)', overflow: 'hidden' }}>
          {WORKSTREAMS.map((ws, i) => (
            <motion.div key={ws.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.2, delay: i * 0.04 + 0.15 }}>
              <WorkstreamRow ws={ws} isLast={i === WORKSTREAMS.length - 1} />
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Day 1 */}
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, delay: 0.14, ease: [0.25,1,0.5,1] }} style={{ marginBottom: 48 }}>
        <SectionHeader label="Day 1 priorities" note="Auto-assigned to department leads at launch · complete within 48 hours" />
        <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', overflow: 'hidden' }}>
          {DAY1_ACTIONS.map((a, i) => (
            <div key={a.id} style={{ display: 'flex', alignItems: 'flex-start', gap: 14, padding: '14px 20px', borderBottom: i < DAY1_ACTIONS.length - 1 ? '1px solid var(--border)' : 'none' }}>
              <div style={{ width: 16, height: 16, border: '1.5px solid var(--border-strong)', borderRadius: 4, flexShrink: 0, marginTop: 2 }} />
              <div style={{ flex: 1 }}>
                <p style={{ fontSize: 13, color: 'var(--ink-800)', lineHeight: 1.45 }}>{a.text}</p>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7, flexShrink: 0 }}>
                <Avatar initials={a.ownerInitials} color={a.ownerColor} size={20} />
                <span style={{ fontSize: 12, color: 'var(--ink-400)', whiteSpace: 'nowrap' }}>{a.owner}</span>
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Footer */}
      {!inWorkspace && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3, delay: 0.2 }}
          style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: 24, borderTop: '1px solid var(--border)' }}>
          <div>
            <p style={{ fontSize: 13, color: 'var(--ink-900)', fontWeight: 500, marginBottom: 2 }}>Ready to begin production?</p>
            <p style={{ fontSize: 12, color: 'var(--ink-400)' }}>Launching notifies your team and activates all Day 1 priorities.</p>
          </div>
          <BtnPrimary onClick={onLaunch} style={{ padding: '13px 36px', fontSize: 14, letterSpacing: '0.01em' }}>
            Launch production →
          </BtnPrimary>
        </motion.div>
      )}
    </div>
  )

  if (inWorkspace) return content

  return (
    <Screen>
      <Topbar
        crumbs={[p.name, 'Production brief']}
        right={
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 12, color: 'var(--ink-400)', fontStyle: 'italic' }}>Review before launching</span>
            <BtnOutline onClick={onBack} style={{ padding: '7px 14px' }}>Back</BtnOutline>
          </div>
        }
      />
      <div style={{ flex: 1, overflowY: 'auto', background: 'var(--surface)' }}>
        {content}
      </div>
    </Screen>
  )
}

function MetaRow({ label, value }) {
  return (
    <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
      <span style={{ fontSize: 11, color: 'var(--ink-400)', letterSpacing: '0.04em', textTransform: 'uppercase', fontWeight: 500, minWidth: 130 }}>{label}</span>
      <span style={{ fontSize: 13, color: 'var(--ink-700)' }}>{value}</span>
    </div>
  )
}

function SectionHeader({ label, note }) {
  return (
    <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 14 }}>
      <p style={{ fontSize: 10, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--ink-500)', fontWeight: 600 }}>{label}</p>
      {note && <p style={{ fontSize: 11, color: 'var(--ink-300)' }}>{note}</p>}
    </div>
  )
}

function WorkstreamRow({ ws, isLast }) {
  const [expanded, setExpanded] = useState(false)
  const pct = Math.round((ws.completedTasks / ws.taskCount) * 100)
  return (
    <div style={{ background: 'var(--surface)', borderBottom: isLast ? 'none' : '1px solid var(--border)' }}>
      <div onClick={() => setExpanded(e => !e)}
        style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 160px 120px 28px', alignItems: 'center', padding: '14px 20px', cursor: 'pointer', gap: 16, transition: 'background 0.12s ease' }}
        onMouseEnter={e => e.currentTarget.style.background = 'var(--ground-dim)'}
        onMouseLeave={e => e.currentTarget.style.background = 'var(--surface)'}
      >
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 5 }}>
            <span style={{ fontSize: 14, fontWeight: 500, color: 'var(--ink-900)' }}>{ws.name}</span>
            {ws.status === 'attention' && (
              <span style={{ fontSize: 10, fontWeight: 500, letterSpacing: '0.04em', padding: '2px 7px', borderRadius: 20, background: 'var(--signal-amber-bg)', color: 'var(--signal-amber-text)' }}>{ws.statusLabel}</span>
            )}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div style={{ flex: 1, maxWidth: 160, height: 2, background: 'var(--ink-100)', borderRadius: 2 }}>
              <div style={{ width: `${pct}%`, height: '100%', background: pct > 0 ? 'var(--signal-green-dot)' : 'var(--ink-200)', borderRadius: 2 }} />
            </div>
            <span style={{ fontSize: 11, color: 'var(--ink-400)', whiteSpace: 'nowrap' }}>{ws.completedTasks} of {ws.taskCount}</span>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Avatar initials={ws.ownerInitials} color={ws.ownerColor} size={24} />
          <span style={{ fontSize: 12, color: 'var(--ink-500)' }}>{ws.owner}</span>
        </div>
        <div>
          <p style={{ fontSize: 11, color: 'var(--ink-400)', marginBottom: 1 }}>Next up</p>
          <p style={{ fontSize: 12, color: 'var(--ink-700)', fontWeight: 500 }}>{ws.nextDeliverable}</p>
          <p style={{ fontSize: 11, color: 'var(--ink-400)' }}>{ws.nextDate}</p>
        </div>
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" style={{ transform: expanded ? 'rotate(90deg)' : 'rotate(0)', transition: 'transform 0.2s ease', flexShrink: 0 }}>
          <path d="M5 3l4 4-4 4" stroke="var(--ink-300)" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </div>
      {expanded && (
        <div style={{ padding: '0 20px 16px 20px', borderTop: '1px solid var(--border)', background: 'var(--ground-dim)' }}>
          <p style={{ fontSize: 10, letterSpacing: '0.06em', textTransform: 'uppercase', color: 'var(--ink-400)', fontWeight: 600, marginBottom: 10, paddingTop: 14 }}>Standard deliverables</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {ws.deliverables.map((d, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <div style={{ width: 14, height: 14, border: i < ws.completedTasks ? 'none' : '1.5px solid var(--border-strong)', borderRadius: 3, flexShrink: 0, background: i < ws.completedTasks ? 'var(--ink-900)' : 'transparent', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  {i < ws.completedTasks && <svg width="8" height="8" viewBox="0 0 8 8" fill="none"><path d="M1 4l2 2 4-4" stroke="white" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
                </div>
                <span style={{ fontSize: 12, color: i < ws.completedTasks ? 'var(--ink-400)' : 'var(--ink-700)', textDecoration: i < ws.completedTasks ? 'line-through' : 'none' }}>{d}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function MilestoneTimeline({ milestones }) {
  return (
    <div style={{ position: 'relative' }}>
      <div style={{ position: 'absolute', top: 6, left: `${(0.5/milestones.length)*100}%`, right: `${(0.5/milestones.length)*100}%`, height: 1, background: 'var(--border-med)' }} />
      <div style={{ display: 'grid', gridTemplateColumns: `repeat(${milestones.length},1fr)`, position: 'relative', zIndex: 1 }}>
        {milestones.map((m, i) => (
          <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <div style={{ marginBottom: 12 }}>
              {m.isEvent ? (
                <div style={{ width: 14, height: 14, borderRadius: '50%', background: 'var(--ink-900)' }} />
              ) : m.done ? (
                <div style={{ width: 12, height: 12, borderRadius: '50%', background: 'var(--ink-900)' }} />
              ) : m.isNext ? (
                <div style={{ width: 12, height: 12, borderRadius: '50%', border: '2px solid var(--ink-700)', background: 'var(--surface)' }} />
              ) : (
                <div style={{ width: 10, height: 10, borderRadius: '50%', border: '1.5px solid var(--border-strong)', background: 'var(--surface)', marginTop: 1 }} />
              )}
            </div>
            <p style={{ fontSize: m.isEvent ? 11 : 10, fontWeight: m.done || m.isEvent || m.isNext ? 600 : 400, color: m.isEvent ? 'var(--ink-900)' : m.done ? 'var(--ink-700)' : m.isNext ? 'var(--ink-800)' : 'var(--ink-500)', textAlign: 'center', lineHeight: 1.3, marginBottom: 3 }}>{m.label}</p>
            <p style={{ fontSize: 10, color: m.isEvent ? 'var(--ink-700)' : 'var(--ink-400)', textAlign: 'center', fontWeight: m.isEvent ? 500 : 400 }}>{m.date}</p>
            {m.sublabel && <p style={{ fontSize: 9, color: m.done ? 'var(--ink-300)' : m.isNext ? 'var(--ink-500)' : 'var(--ink-300)', marginTop: 2, letterSpacing: '0.02em', textAlign: 'center' }}>{m.sublabel}</p>}
          </div>
        ))}
      </div>
    </div>
  )
}
