/* ─────────────────────────────────────────────────────────
   Shared Library Data — single source of truth
   Team · Vendors · Venues · Inventory
   ─────────────────────────────────────────────────────── */

/* Team directory data lives in src/data/capeDirectory.js — single source of truth */

/* ══════════════════════════════════════════════════════════
   VENDOR LIBRARY
   ══════════════════════════════════════════════════════════ */
export const VENDOR_CATS    = ['All','AV / Interactive','Fabrication','Catering','Florals','Logistics','Rentals','Content','Printing','Staffing','Security','Lighting','Audio']
export const VENDOR_CITIES  = ['All','New York','Los Angeles','London','Paris','Miami','Austin','Chicago','Seattle']

export const VENDORS = [
  { id:'v01', name:'Ocubo Digital',        category:'AV / Interactive', preferred:true,  contact:'Sara Mendes',      email:'sara@ocubo.com',            phone:'(646) 555-0200', website:'ocubodigital.com',      city:'New York',     location:'New York, NY',       services:['LED walls','Interactive touchscreens','Custom software','Projection mapping'],                   pricing:'$40K–$200K per project',       pastProjects:['Apple Dinner','Spotify SXSW','Cartier NY'],   notes:'Primary AV vendor. Excellent on complex interactive builds. Long lead times — book 10+ weeks out.' },
  { id:'v02', name:'Eventmakers NYC',      category:'Fabrication',      preferred:true,  contact:'Tom Ricci',         email:'tom@eventmakers.com',       phone:'(212) 555-0210', website:'eventmakersnyc.com',    city:'New York',     location:'Long Island City, NY', services:['Scenic fabrication','Custom furniture','Signage','Paint & finish'],                              pricing:'$20K–$500K per build',         pastProjects:['Apple Dinner','Nike Paris','Moncler Milan'],  notes:'Gold-standard scenic. Tom Ricci is our primary contact. Strong on tight timelines.' },
  { id:'v03', name:'Glasshouse Catering',  category:'Catering',         preferred:true,  contact:'Nina Park',         email:'nina@glasshouse.nyc',       phone:'(917) 555-0220', website:'glasshouse.nyc',        city:'New York',     location:'New York, NY',       services:['Plated dinner','Passed canapés','Beverage programs','Staffing'],                                pricing:'$180–$320 per head',           pastProjects:['Apple Dinner','Cartier NY Gala'],             notes:'Preferred for high-end seated dinners. Minimum 80 guests. Always ask for Nina.' },
  { id:'v04', name:'Aria Florals',         category:'Florals',          preferred:true,  contact:'Cleo Stein',        email:'cleo@ariaflorals.com',      phone:'(917) 555-0250', website:'ariaflorals.com',       city:'New York',     location:'Brooklyn, NY',       services:['Table arrangements','Entrance installations','Floral sculpture','Seasonal sourcing'],            pricing:'$8K–$80K per project',         pastProjects:['Apple Dinner','Cartier NY Gala','Hermès NYC'], notes:'Best for sculptural and architectural floral work. Cleo leads all CAPE projects personally.' },
  { id:'v05', name:'Peak Freight',         category:'Logistics',        preferred:false, contact:'Maria Fuentes',     email:'maria@peakfreight.com',     phone:'(718) 555-0240', website:'peakfreight.com',       city:'New York',     location:'Queens, NY',         services:['White-glove freight','Crated transport','Expedited delivery','Customs coordination'],           pricing:'Project-dependent',            pastProjects:['Apple Dinner','Nike Paris'],                  notes:'Reliable for NYC and tri-state. Need 72hr notice minimum. Quote pending for Paris routes.' },
  { id:'v06', name:'Classic Party Rentals',category:'Rentals',          preferred:true,  contact:'Devon Wu',          email:'devon@classicrentals.com',  phone:'(212) 555-0260', website:'classicpartyrentals.com',city:'New York',    location:'New York, NY',       services:['Glassware','Linens','Furniture','China','Flatware'],                                            pricing:'Quote on request',             pastProjects:['Apple Dinner','Cartier NY Gala','Hermès NYC'], notes:'Go-to for tablescaping. Large inventory, reliable delivery. Always confirm 3 weeks out.' },
  { id:'v07', name:'Limelight Studios',    category:'Content',          preferred:true,  contact:'Drew Callahan',     email:'drew@limelight.com',        phone:'(646) 555-0230', website:'limelightstudios.com',  city:'New York',     location:'New York, NY',       services:['Photography','Video production','Recap edits','Social content'],                                pricing:'$15K–$60K per project',         pastProjects:['Apple Dinner','Nike Paris','Moncler Milan'],  notes:'Primary content partner. Fast turnaround on same-day edits. Always book Drew directly.' },
  { id:'v08', name:'Linen Lab NYC',        category:'Rentals',          preferred:true,  contact:'Priya Shah',        email:'priya@linenlab.com',        phone:'(212) 555-0270', website:'linenlab.com',          city:'New York',     location:'New York, NY',       services:['Custom linens','Tablecloths','Napkins','Chair covers'],                                         pricing:'$12–$85 per piece',            pastProjects:['Apple Dinner','Cartier NY Gala'],             notes:'Best for custom and bespoke linen. 6-week minimum lead time for custom colours.' },
  { id:'v09', name:'Prestige Spirits',     category:'Catering',         preferred:false, contact:'Alex Brennan',      email:'alex@prestigespirits.com',  phone:'(212) 555-0280', website:'prestigespirits.com',   city:'New York',     location:'New York, NY',       services:['Premium beverage programming','Bar staffing','Spirit selection','Wine curation'],               pricing:'$45–$120 per head',            pastProjects:['Apple Dinner'],                               notes:'Excellent sommelier team. Good for premium wine and spirit programs. Use alongside Glasshouse.' },
  { id:'v10', name:'Technicraft London',   category:'AV / Interactive', preferred:false, contact:'James Aldred',      email:'james@technicraft.co.uk',   phone:'+44 207 555 0290',website:'technicraft.co.uk',     city:'London',       location:'London, UK',         services:['LED production','Audio systems','Lighting rigs','Technical direction'],                         pricing:'£25K–£200K per project',       pastProjects:['Adidas London','Burberry SS26'],               notes:'Strong on large-format audio/visual for UK events.' },
  { id:'v11', name:'Mise en Scène Paris',  category:'Fabrication',      preferred:false, contact:'Sophie Renard',     email:'sophie@misescene.fr',       phone:'+33 1 555 0291', website:'misescene.fr',          city:'Paris',        location:'Paris, France',      services:['Scenic design','Set builds','Art installation','Display systems'],                              pricing:'€30K–€400K per project',       pastProjects:['Prada Paris','LV Paris'],                     notes:'Raph\'s primary Paris fabrication contact. Requires French contracts. 12-week lead time.' },
  { id:'v12', name:'Staffmark Events',     category:'Staffing',         preferred:true,  contact:'Lauren Mills',      email:'lauren@staffmark.com',      phone:'(212) 555-0295', website:'staffmark.com',         city:'New York',     location:'New York, NY',       services:['Event staff','Brand ambassadors','Registration teams','Coat check'],                            pricing:'$28–$55 per hour',             pastProjects:['Apple Dinner','Nike Paris','Cartier NY Gala'], notes:'Reliable staffing partner across all CAPE New York events. Always request Lauren\'s team.' },
  { id:'v13', name:'Vivid Sound LA',       category:'Audio',            preferred:false, contact:'Carlos Reyes',      email:'carlos@vividsound.com',     phone:'(310) 555-0300', website:'vividsoundla.com',      city:'Los Angeles',  location:'Los Angeles, CA',    services:['PA systems','Wireless microphones','DJ setups','Acoustic panels'],                              pricing:'$8K–$60K per event',           pastProjects:['Balenciaga LA'],                              notes:'Recommended for LA activations. Strong live sound team. Carlos is excellent.' },
  { id:'v14', name:'Greenfield Lighting',  category:'Lighting',         preferred:false, contact:'Ben Hart',          email:'ben@greenfieldlighting.com',phone:'(212) 555-0305', website:'greenfieldlighting.com',city:'New York',     location:'New York, NY',       services:['Lighting design','Rig installation','DMX programming','Spotlights'],                            pricing:'$12K–$80K per event',          pastProjects:['Cartier NY Gala','Moncler Milan'],            notes:'Strong lighting design capability. Ben Hart is our contact — always request him.' },
]

/* ══════════════════════════════════════════════════════════
   VENUE LIBRARY
   ══════════════════════════════════════════════════════════ */
export const VENUE_CITIES  = ['All','New York','Los Angeles','London','Paris','Miami','Austin','Chicago','Tokyo','Dubai','Milan']
export const VENUE_TYPES   = ['All','Rooftop','Gallery','Hotel','Warehouse','Museum','Restaurant','Private Club','Outdoor','Ballroom']
export const VENUE_CAPACITY = ['All','Under 50','50–100','100–250','250–500','500+']

export const VENUES = [
  { id:'vn01', name:'Brooklyn Tower — Sky Lounge', city:'New York', location:'9 DeKalb Ave, Brooklyn, NY 11201', website:'brooklyintower.com', type:'Rooftop', indoorOutdoor:'Indoor', capacity:250, sqft:12500, ceilingHeight:"14 ft", floor:'73rd Floor — Sky Lounge', buildingHours:'7:00 AM – 12:00 AM', preferred:true,
    power:'200A, 3-Phase', dedicatedCircuits:'Yes — 4 dedicated 20A circuits', floorBoxes:'8 floor boxes (20A)', wifi:'Building wifi available', hardline:'Cat6 available via patch panel',
    dockAddress:'Rear of building, Dock A, enter on Willoughby St', dockHours:'8:00 AM – 6:00 PM', dockReservation:'Yes — 48hr advance required', dockContact:'Dock Manager · (212) 555-0191',
    passengerElevQty:4, passengerElevDims:'54"W x 84"D x 96"H', passengerElevDoorWidth:'36"', passengerElevWeight:'3,500 lbs',
    freightElevQty:1, freightElevDims:'84"W x 120"D x 96"H', freightElevDoorWidth:'60"', freightElevWeight:'10,000 lbs',
    maxCrateSize:'80"W x 110"D x 90"H', maxPalletSize:'48" x 48"', vendorParking:'Street parking only — no dedicated vendor lot', guestParking:'City Point garage adjacent (validated)',
    openFlame:'No open flame permitted', noiseRestrictions:'Music off by 11:00 PM', curfew:'Building access until midnight', buildingRules:'All vendors must check in at Dock A with photo ID',
    contact:'James Holter', contactTitle:'Venue Director', contactPhone:'(212) 555-0189', contactEmail:'james@brooklyntower.com', preferredVendors:['Ocubo Digital','Glasshouse Catering','Classic Party Rentals'], pastProjects:['Apple Dinner'],
    notes:'73rd floor Sky Lounge. 200A 3-phase power. Dock A, Willoughby St entrance. Reservation required 48hr advance. No open flame.' },

  { id:'vn02', name:'Spring Studios', city:'New York', location:'50 Varick St, New York, NY 10013', website:'springstudios.com', type:'Warehouse', indoorOutdoor:'Indoor', capacity:800, sqft:28000, ceilingHeight:"18 ft", floor:'4 floors — full building', buildingHours:'6:00 AM – 2:00 AM', preferred:true,
    power:'400A, 3-Phase', dedicatedCircuits:'Yes — 8 dedicated 20A circuits per floor', floorBoxes:'16 floor boxes total', wifi:'Dedicated event wifi network', hardline:'Cat6 + fiber backbone available',
    dockAddress:'Varick St loading dock, ground level', dockHours:'24-hour access with reservation', dockReservation:'Yes — 72hr advance required', dockContact:'Operations Desk · (212) 555-0401',
    passengerElevQty:3, passengerElevDims:'60"W x 90"D x 96"H', passengerElevDoorWidth:'42"', passengerElevWeight:'4,000 lbs',
    freightElevQty:2, freightElevDims:'96"W x 140"D x 108"H', freightElevDoorWidth:'72"', freightElevWeight:'15,000 lbs',
    maxCrateSize:'90"W x 130"D x 100"H', maxPalletSize:'48" x 48"', vendorParking:'On-site loading area, 6 vendor spots', guestParking:'Varick St garage two blocks south',
    openFlame:'Permitted with fire marshal approval', noiseRestrictions:'No restriction — industrial building', curfew:'24-hour access', buildingRules:'Floor protection required for all builds',
    contact:'Rachel Kim', contactTitle:'Events Director', contactPhone:'(212) 555-0400', contactEmail:'rachel@springstudios.com', preferredVendors:['Eventmakers NYC','Ocubo Digital'], pastProjects:['Cartier NY Gala','Spotify SXSW'],
    notes:'Four floors of raw industrial space. Strong natural light on upper floors. Loading dock on Varick.' },

  { id:'vn03', name:'Sunset Room — Soho House NY', city:'New York', location:'29-35 9th Ave, New York, NY 10014', website:'sohohouse.com', type:'Private Club', indoorOutdoor:'Both', capacity:180, sqft:6400, ceilingHeight:"10 ft", floor:'Rooftop level', buildingHours:'8:00 AM – 2:00 AM', preferred:false,
    power:'100A, single-phase', dedicatedCircuits:'2 dedicated 20A circuits', floorBoxes:'4 floor boxes', wifi:'Member wifi network, guest passes available', hardline:'Not available',
    dockAddress:'No dedicated loading dock — street-level access only', dockHours:'9:00 AM – 5:00 PM load-in window', dockReservation:'Yes — coordinate with events team', dockContact:'Tom Barton · (212) 555-0410',
    passengerElevQty:2, passengerElevDims:'48"W x 72"D x 84"H', passengerElevDoorWidth:'32"', passengerElevWeight:'2,500 lbs',
    freightElevQty:0, freightElevDims:'Not available', freightElevDoorWidth:'—', freightElevWeight:'—',
    maxCrateSize:'40"W x 60"D x 78"H (passenger elevator limit)', maxPalletSize:'Not accommodated', vendorParking:'No on-site parking', guestParking:'Nearby paid garages, no validation',
    openFlame:'Candles only, no open flame cooking', noiseRestrictions:'Music off by 10:00 PM (residential building)', curfew:'Members-only access after 10:00 PM', buildingRules:'Members-only access requirements throughout',
    contact:'Tom Barton', contactTitle:'Events Manager', contactPhone:'(212) 555-0410', contactEmail:'tom@sohonyc.com', preferredVendors:['Glasshouse Catering'], pastProjects:[],
    notes:'Members-only access requirements. Contact Tom 12 weeks out minimum. Rooftop available May–Oct only.' },

  { id:'vn04', name:'The Standard Biergarten — Rooftop', city:'New York', location:'848 Washington St, New York, NY 10014', website:'standardhotels.com', type:'Rooftop', indoorOutdoor:'Outdoor', capacity:300, sqft:8000, ceilingHeight:'Open', floor:'18th floor rooftop', buildingHours:'10:00 AM – 1:00 AM', preferred:false,
    power:'100A, single-phase', dedicatedCircuits:'2 dedicated 20A circuits', floorBoxes:'No floor boxes — overhead power drops only', wifi:'Hotel guest wifi extends to rooftop', hardline:'Not available',
    dockAddress:'Washington St service entrance', dockHours:'7:00 AM – 11:00 AM', dockReservation:'Yes — 1 week advance required', dockContact:'Amy Sandler · (212) 555-0420',
    passengerElevQty:2, passengerElevDims:'48"W x 80"D x 90"H', passengerElevDoorWidth:'36"', passengerElevWeight:'3,000 lbs',
    freightElevQty:1, freightElevDims:'60"W x 90"D x 96"H', freightElevDoorWidth:'48"', freightElevWeight:'5,000 lbs',
    maxCrateSize:'55"W x 85"D x 90"H', maxPalletSize:'Not recommended — narrow service corridors', vendorParking:'No dedicated lot — street loading zone permit required', guestParking:'Valet available, hotel rate applies',
    openFlame:'Outdoor open flame permitted with FDNY permit', noiseRestrictions:'Amplified music permit required, off by 11:00 PM', curfew:'Weather-dependent — no cover', buildingRules:'Weather contingency plan required for all bookings',
    contact:'Amy Sandler', contactTitle:'Private Events', contactPhone:'(212) 555-0420', contactEmail:'events@thestandard.com', preferredVendors:[], pastProjects:[],
    notes:'Open air. Weather contingency required. Permits needed for amplified music.' },

  { id:'vn05', name:'Pendry West Hollywood', city:'Los Angeles', location:'8430 Sunset Blvd, West Hollywood, CA 90069', website:'pendryhotels.com', type:'Hotel', indoorOutdoor:'Both', capacity:400, sqft:14000, ceilingHeight:"12 ft", floor:'Ballroom + terrace, ground level', buildingHours:'6:00 AM – 2:00 AM', preferred:true,
    power:'200A, 3-Phase', dedicatedCircuits:'6 dedicated 20A circuits in ballroom', floorBoxes:'10 floor boxes', wifi:'Dedicated event network available', hardline:'Cat6 throughout ballroom',
    dockAddress:'Sunset Plaza service entrance, rear of property', dockHours:'6:00 AM – 10:00 PM', dockReservation:'Yes — 48hr advance required', dockContact:'Sofia Reyes · (310) 555-0430',
    passengerElevQty:3, passengerElevDims:'56"W x 84"D x 96"H', passengerElevDoorWidth:'40"', passengerElevWeight:'4,000 lbs',
    freightElevQty:1, freightElevDims:'80"W x 110"D x 100"H', freightElevDoorWidth:'56"', freightElevWeight:'8,000 lbs',
    maxCrateSize:'75"W x 105"D x 95"H', maxPalletSize:'48" x 48"', vendorParking:'On-site loading area, 4 vendor spots', guestParking:'Valet available, validated rate for events',
    openFlame:'Permitted with hotel fire watch staff', noiseRestrictions:'Amplified sound off by midnight', curfew:'Full hotel buyout extends access to 2:00 AM', buildingRules:'COI required for all vendors',
    contact:'Sofia Reyes', contactTitle:'Director of Events', contactPhone:'(310) 555-0430', contactEmail:'sofia@pendryhotels.com', preferredVendors:['Vivid Sound LA'], pastProjects:['Balenciaga LA'],
    notes:'Full hotel buyout available. Strong AV infrastructure in ballroom. Preferred for LA activations.' },

  { id:'vn06', name:'Paley Center for Media', city:'Los Angeles', location:'465 N Beverly Dr, Beverly Hills, CA 90210', website:'paleycenter.org', type:'Museum', indoorOutdoor:'Indoor', capacity:350, sqft:11000, ceilingHeight:"16 ft", floor:'Main gallery + theater, ground level', buildingHours:'8:00 AM – 11:00 PM', preferred:false,
    power:'150A, 3-Phase', dedicatedCircuits:'4 dedicated 20A circuits', floorBoxes:'6 floor boxes', wifi:'Guest wifi available, limited bandwidth', hardline:'Not available — bring your own',
    dockAddress:'Rear alley loading entrance off Beverly Dr', dockHours:'8:00 AM – 6:00 PM', dockReservation:'Yes — 1 week advance required', dockContact:'David Park · (310) 555-0440',
    passengerElevQty:2, passengerElevDims:'50"W x 78"D x 88"H', passengerElevDoorWidth:'36"', passengerElevWeight:'3,000 lbs',
    freightElevQty:1, freightElevDims:'70"W x 100"D x 96"H', freightElevDoorWidth:'48"', freightElevWeight:'6,000 lbs',
    maxCrateSize:'65"W x 95"D x 90"H', maxPalletSize:'40" x 48"', vendorParking:'Limited — 2 spots, street parking nearby', guestParking:'Validated garage parking, 200 spaces',
    openFlame:'No open flame — museum collection on premises', noiseRestrictions:'Music off by 10:00 PM', curfew:'Building closes 11:00 PM', buildingRules:'No adhesives or hardware on walls — museum policy',
    contact:'David Park', contactTitle:'Venue Manager', contactPhone:'(310) 555-0440', contactEmail:'david@paleycenter.org', preferredVendors:[], pastProjects:[],
    notes:'Strong for press and media events. Excellent natural light. Tech infrastructure is dated — bring your own AV.' },

  { id:'vn07', name:'The OXO Tower — Riverside Room', city:'London', location:'Barge House St, London SE1 9PH, UK', website:'oxotower.co.uk', type:'Gallery', indoorOutdoor:'Indoor', capacity:220, sqft:7500, ceilingHeight:"11 ft", floor:'8th floor — Riverside Room', buildingHours:'8:00 AM – 12:00 AM', preferred:true,
    power:'32A, 3-Phase (UK standard)', dedicatedCircuits:'4 dedicated 16A circuits', floorBoxes:'6 floor boxes', wifi:'Building wifi available', hardline:'Available on request',
    dockAddress:'Riverside service entrance, Barge House St', dockHours:'7:00 AM – 7:00 PM', dockReservation:'Yes — 48hr advance required', dockContact:'Fiona Walsh · +44 20 7803 3888',
    passengerElevQty:2, passengerElevDims:'130cm W x 200cm D x 230cm H', passengerElevDoorWidth:'90cm', passengerElevWeight:'1,200 kg',
    freightElevQty:1, freightElevDims:'180cm W x 250cm D x 230cm H', freightElevDoorWidth:'140cm', freightElevWeight:'2,500 kg',
    maxCrateSize:'170cm W x 240cm D x 220cm H', maxPalletSize:'120cm x 100cm (EUR pallet)', vendorParking:'No on-site parking — congestion charge zone', guestParking:'Public car parks nearby, no validation',
    openFlame:'No open flame', noiseRestrictions:'Licensed until midnight', curfew:'Building closes midnight', buildingRules:'French-only contracts not applicable — UK venue',
    contact:'Fiona Walsh', contactTitle:'Events Manager', contactPhone:'+44 20 7803 3888', contactEmail:'events@oxotower.co.uk', preferredVendors:['Technicraft London'], pastProjects:['Adidas London'],
    notes:'Stunning Thames views. Strong freight lift access from riverside. Licensed until midnight.' },

  { id:'vn08', name:'Palais de Tokyo — Salle de Bal', city:'Paris', location:'13 Ave du Président Wilson, 75116 Paris', website:'palaisdetokyo.com', type:'Museum', indoorOutdoor:'Indoor', capacity:600, sqft:22000, ceilingHeight:"22 ft", floor:'Salle de Bal, ground level', buildingHours:'8:00 AM – 1:00 AM', preferred:false,
    power:'63A, 3-Phase (EU standard)', dedicatedCircuits:'8 dedicated 16A circuits', floorBoxes:'12 floor boxes', wifi:'Event wifi network available', hardline:'Fiber available with advance request',
    dockAddress:'Quai de Tokyo service entrance', dockHours:'7:00 AM – 8:00 PM', dockReservation:'Yes — 1 week advance required', dockContact:'Marie Dupont · +33 1 47 23 54 01',
    passengerElevQty:2, passengerElevDims:'140cm W x 220cm D x 230cm H', passengerElevDoorWidth:'100cm', passengerElevWeight:'1,500 kg',
    freightElevQty:2, freightElevDims:'250cm W x 350cm D x 280cm H', freightElevDoorWidth:'200cm', freightElevWeight:'5,000 kg',
    maxCrateSize:'240cm W x 340cm D x 270cm H', maxPalletSize:'120cm x 100cm (EUR pallet)', vendorParking:'Limited on-site, 3 spots', guestParking:'Public parking on Avenue du Président Wilson',
    openFlame:'No open flame — museum collection', noiseRestrictions:'Music permitted until 1:00 AM with permit', curfew:'1:00 AM building close', buildingRules:'French-only contracts required. Very high ceilings, good rigging points.',
    contact:'Marie Dupont', contactTitle:'Événements', contactPhone:'+33 1 47 23 54 01', contactEmail:'events@palaisdetokyo.com', preferredVendors:['Mise en Scène Paris'], pastProjects:['Prada Paris'],
    notes:'Spectacular brutalist space. Very high ceilings, good rigging points. French-only contracts.' },

  { id:'vn09', name:'1 Hotel South Beach', city:'Miami', location:'2341 Collins Ave, Miami Beach, FL 33139', website:'1hotels.com', type:'Hotel', indoorOutdoor:'Both', capacity:500, sqft:18000, ceilingHeight:"14 ft", floor:'Ballroom + terraces, ground & 2nd floor', buildingHours:'6:00 AM – 2:00 AM', preferred:false,
    power:'200A, 3-Phase', dedicatedCircuits:'6 dedicated 20A circuits', floorBoxes:'8 floor boxes', wifi:'Event-grade wifi available', hardline:'Cat6 in ballroom',
    dockAddress:'Collins Ave rear service entrance', dockHours:'6:00 AM – 9:00 PM', dockReservation:'Yes — 1 week advance required', dockContact:'Carlos Vega · (305) 555-0460',
    passengerElevQty:3, passengerElevDims:'56"W x 84"D x 96"H', passengerElevDoorWidth:'40"', passengerElevWeight:'4,000 lbs',
    freightElevQty:1, freightElevDims:'78"W x 108"D x 100"H', freightElevDoorWidth:'54"', freightElevWeight:'7,500 lbs',
    maxCrateSize:'72"W x 100"D x 95"H', maxPalletSize:'48" x 48"', vendorParking:'On-site loading area, 4 vendor spots', guestParking:'Valet available, validated event rate',
    openFlame:'Outdoor terrace only, with fire watch', noiseRestrictions:'South Beach noise ordinance — off by midnight', curfew:'City permitting required for large outdoor events', buildingRules:'South Beach permitting required for outdoor amplified sound',
    contact:'Carlos Vega', contactTitle:'Events Director', contactPhone:'(305) 555-0460', contactEmail:'carlos@1hotels.com', preferredVendors:[], pastProjects:['Dior Miami'],
    notes:'Eco-luxury hotel. Strong outdoor terraces. South Beach permitting required for large outdoor events.' },

  { id:'vn10', name:'Eataly Rooftop — La Terrazza', city:'New York', location:'200 5th Ave, New York, NY 10010', website:'eataly.com', type:'Rooftop', indoorOutdoor:'Outdoor', capacity:150, sqft:4500, ceilingHeight:'Open', floor:'Rooftop, 5th floor', buildingHours:'11:00 AM – 11:00 PM (seasonal)', preferred:false,
    power:'60A, single-phase', dedicatedCircuits:'2 dedicated 20A circuits', floorBoxes:'No floor boxes', wifi:'Limited rooftop wifi', hardline:'Not available',
    dockAddress:'5th Ave service entrance', dockHours:'9:00 AM – 4:00 PM', dockReservation:'Yes — coordinate with events team', dockContact:'Marco Rossi · (212) 555-0470',
    passengerElevQty:2, passengerElevDims:'48"W x 76"D x 88"H', passengerElevDoorWidth:'36"', passengerElevWeight:'2,800 lbs',
    freightElevQty:0, freightElevDims:'Not available', freightElevDoorWidth:'—', freightElevWeight:'—',
    maxCrateSize:'42"W x 70"D x 80"H (passenger elevator limit)', maxPalletSize:'Not accommodated', vendorParking:'No on-site parking', guestParking:'Nearby paid garages',
    openFlame:'No open flame — exclusive Eataly catering only', noiseRestrictions:'Music off by 10:00 PM', curfew:'Seasonal closure November–March', buildingRules:'Exclusive catering through Eataly required',
    contact:'Marco Rossi', contactTitle:'Events Manager', contactPhone:'(212) 555-0470', contactEmail:'marco@eataly.com', preferredVendors:['Glasshouse Catering'], pastProjects:[],
    notes:'Seasonal only (April–October). Exclusive catering through Eataly required. Stunning city views.' },

  { id:'vn11', name:'Soho Warehouse — Great Hall', city:'Los Angeles', location:'1000 S Santa Fe Ave, Los Angeles, CA 90021', website:'sohowarehouse.com', type:'Warehouse', indoorOutdoor:'Indoor', capacity:700, sqft:25000, ceilingHeight:"20 ft", floor:'Ground floor — Great Hall', buildingHours:'24-hour access for members', preferred:false,
    power:'400A, 3-Phase', dedicatedCircuits:'10 dedicated 20A circuits', floorBoxes:'14 floor boxes', wifi:'Member wifi network', hardline:'Cat6 available',
    dockAddress:'Santa Fe Ave loading dock', dockHours:'24-hour access with reservation', dockReservation:'Yes — 1 week advance required', dockContact:'Jen Liu · (213) 555-0480',
    passengerElevQty:2, passengerElevDims:'60"W x 90"D x 100"H', passengerElevDoorWidth:'42"', passengerElevWeight:'4,500 lbs',
    freightElevQty:2, freightElevDims:'100"W x 150"D x 110"H', freightElevDoorWidth:'80"', freightElevWeight:'16,000 lbs',
    maxCrateSize:'95"W x 140"D x 105"H', maxPalletSize:'48" x 48"', vendorParking:'On-site lot, 10+ vendor spots', guestParking:'On-site member parking',
    openFlame:'Permitted with fire marshal approval', noiseRestrictions:'No restriction — industrial zone', curfew:'24-hour access for members', buildingRules:'Members-only access for some spaces',
    contact:'Jen Liu', contactTitle:'Private Events', contactPhone:'(213) 555-0480', contactEmail:'events@sohowarehouse.com', preferredVendors:[], pastProjects:[],
    notes:'Massive raw warehouse. Members-only access for some spaces. Excellent for large activations.' },

  { id:'vn12', name:'Armani Silos — Exhibition Hall', city:'Milan', location:'Via Bergognone 40, 20144 Milan, Italy', website:'armanisilos.com', type:'Museum', indoorOutdoor:'Indoor', capacity:300, sqft:10000, ceilingHeight:"18 ft", floor:'Ground floor exhibition hall', buildingHours:'9:00 AM – 11:00 PM', preferred:true,
    power:'63A, 3-Phase (EU standard)', dedicatedCircuits:'6 dedicated 16A circuits', floorBoxes:'8 floor boxes', wifi:'Event wifi available', hardline:'Available with advance request',
    dockAddress:'Via Bergognone rear service entrance', dockHours:'8:00 AM – 7:00 PM', dockReservation:'Yes — 1 week advance required', dockContact:'Giulia Moretti · +39 02 5678 9012',
    passengerElevQty:2, passengerElevDims:'140cm W x 210cm D x 230cm H', passengerElevDoorWidth:'100cm', passengerElevWeight:'1,400 kg',
    freightElevQty:1, freightElevDims:'220cm W x 300cm D x 260cm H', freightElevDoorWidth:'180cm', freightElevWeight:'4,000 kg',
    maxCrateSize:'210cm W x 290cm D x 250cm H', maxPalletSize:'120cm x 100cm (EUR pallet)', vendorParking:'Limited on-site, 2 spots', guestParking:'Public parking nearby',
    openFlame:'No open flame — converted factory with collection on premises', noiseRestrictions:'Music permitted until 11:00 PM', curfew:'11:00 PM building close', buildingRules:'Works best with Italian-speaking production liaisons',
    contact:'Giulia Moretti', contactTitle:'Venue Manager', contactPhone:'+39 02 5678 9012', contactEmail:'events@armanisilos.com', preferredVendors:['Mise en Scène Paris'], pastProjects:['Moncler Milan'],
    notes:'Stunning converted factory. Excellent rigging capability. Works best with Italian-speaking production liaisons.' },
]
export const INV_CATS    = ['All','Furniture','Lighting','AV / Tech','Fabric & Linens','Display','Signage','Décor','Tools & Hardware','Cases & Storage']
export const INV_LOCATIONS = ['All','New York Warehouse','LA Storage','London Office','Paris Studio']
export const INV_CONDITIONS = ['All','Excellent','Good','Fair','Needs repair']

export const INVENTORY = [
  { id:'i01', name:'Custom Black Steel Dining Tables (×12)',    category:'Furniture',      qty:12, unit:'tables',   condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Apple Dinner','Cartier NY Gala'], notes:'8ft rectangular. Powder-coated matte black legs, walnut veneer tops. Minor scratches on 2 tops.',                                 dimensions:'96" × 36" × 30"',       purchaseYear:2024 },
  { id:'i02', name:'Ghost Chairs (×60)',                        category:'Furniture',      qty:60, unit:'chairs',   condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala','Hermès NYC'],  notes:'Kartell Ghost chairs. 55 in good condition, 5 have minor scuffs.',                                                             dimensions:'Standard',               purchaseYear:2023 },
  { id:'i03', name:'Riedel Veritas Wine Glasses (×240)',        category:'Furniture',      qty:240,unit:'glasses',  condition:'Good',       storage:'New York Warehouse', available:false, projects:['Apple Dinner'],                  notes:'Out for Apple Dinner. Return expected Jul 17.',                                                                                dimensions:'Standard 14oz',          purchaseYear:2025 },
  { id:'i04', name:'Custom Lounge Sectional — Cream Boucle',   category:'Furniture',      qty:2,  unit:'sets',     condition:'Excellent',  storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala'],               notes:'Two modular sectional sets. 4 pieces each. Professional clean after last event. Ready for use.',                                dimensions:'Variable configuration', purchaseYear:2024 },
  { id:'i05', name:'Astera Titan LED Tubes (×24)',              category:'Lighting',       qty:24, unit:'units',    condition:'Excellent',  storage:'New York Warehouse', available:false, projects:['Apple Dinner'],                  notes:'Currently deployed at Apple Dinner. Return Jul 17. Includes charging cases.',                                                  dimensions:'47" length',             purchaseYear:2025 },
  { id:'i06', name:'Robe T1 Profile Spotlights (×12)',          category:'Lighting',       qty:12, unit:'fixtures', condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala','Moncler Milan'],notes:'2 units need lamp replacement. Order placed. All DMX tested post-Moncler.',                                                    dimensions:'Standard',               purchaseYear:2022 },
  { id:'i07', name:'LED Par Cans 64 (×48)',                     category:'Lighting',       qty:48, unit:'units',    condition:'Fair',       storage:'New York Warehouse', available:true,  projects:['Spotify SXSW','Nike Paris'],     notes:'Older stock. 6 need recabling. Suitable for uplighting and colour wash. Not for primary lighting.',                            dimensions:'Standard',               purchaseYear:2020 },
  { id:'i08', name:'Martin MAC Aura XB Wash (×8)',              category:'Lighting',       qty:8,  unit:'fixtures', condition:'Excellent',  storage:'New York Warehouse', available:true,  projects:['Apple Dinner'],                  notes:'High-performance LED wash. Excellent condition after Apple maintenance check.',                                                 dimensions:'Standard',               purchaseYear:2025 },
  { id:'i09', name:'Shure Axient Wireless System (8ch)',        category:'AV / Tech',      qty:1,  unit:'system',   condition:'Excellent',  storage:'New York Warehouse', available:false, projects:['Apple Dinner'],                  notes:'Out for Apple Dinner. 8 channels, 6 handhelds + 2 lavs. Return Jul 17.',                                                       dimensions:'Rack-mount',             purchaseYear:2025 },
  { id:'i10', name:'Dante Audio Network Rack',                  category:'AV / Tech',      qty:1,  unit:'rack',     condition:'Good',       storage:'New York Warehouse', available:false, projects:['Apple Dinner'],                  notes:'Lake LM44 processing, Dante distribution. Out for Apple Dinner. Return Jul 17.',                                               dimensions:'6U rack',                purchaseYear:2024 },
  { id:'i11', name:'iPad Pros 12.9" (×8)',                      category:'AV / Tech',      qty:8,  unit:'devices',  condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala','Apple Dinner'],notes:'Used for digital guestlist, signage, and program displays. Charging cases included.',                                          dimensions:'12.9 inch',              purchaseYear:2023 },
  { id:'i12', name:'4K Presentation Laptop Kit',                category:'AV / Tech',      qty:3,  unit:'kits',     condition:'Excellent',  storage:'New York Warehouse', available:true,  projects:['Apple Dinner'],                  notes:'MacBook Pro M3 × 3. HDMI, adapters, decks loaded. Clean and updated.',                                                        dimensions:'Standard',               purchaseYear:2025 },
  { id:'i13', name:'White 132" Round Linens (×20)',             category:'Fabric & Linens',qty:20, unit:'linens',   condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Apple Dinner','Cartier NY Gala'],notes:'Professional cleaned after Apple Dinner. 2 have small stains. Suitable for non-premium use.',                                  dimensions:'132 inch round',         purchaseYear:2024 },
  { id:'i14', name:'Stone Linen Napkins (×300)',                category:'Fabric & Linens',qty:300,unit:'pieces',   condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Apple Dinner'],                  notes:'Laundered and pressed. Stone colourway. Complement the white round linens.',                                                   dimensions:'20" × 20"',              purchaseYear:2025 },
  { id:'i15', name:'Black Velvet Stanchions (×20)',             category:'Display',        qty:20, unit:'units',    condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala','Hermès NYC'],  notes:'Gold-tipped posts. Black velvet rope. All complete pairs.',                                                                    dimensions:'36" height',             purchaseYear:2022 },
  { id:'i16', name:'Acrylic Display Pedestals — Assorted',      category:'Display',        qty:12, unit:'units',    condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala'],               notes:'4 × 12", 4 × 18", 4 × 24" heights. Clear acrylic. Minor scratching on 3 units.',                                             dimensions:'12"–24" height',         purchaseYear:2023 },
  { id:'i17', name:'3M Vinyl Cutter & Weeder Kit',              category:'Signage',        qty:1,  unit:'kit',      condition:'Excellent',  storage:'New York Warehouse', available:true,  projects:[],                                notes:'Graphtec FC9000-75. Excellent condition. Used for on-site vinyl adjustments.',                                                  dimensions:'Desktop unit',           purchaseYear:2024 },
  { id:'i18', name:'Portable A-Frame Signs (×10)',              category:'Signage',        qty:10, unit:'units',    condition:'Fair',       storage:'New York Warehouse', available:true,  projects:['Spotify SXSW'],                  notes:'Metal frame, snap-open face. Needs cleaning. 2 have bent frames — usable but not premium.',                                   dimensions:'24" × 36"',              purchaseYear:2021 },
  { id:'i19', name:'Curated Artbook Library (×80 volumes)',     category:'Décor',          qty:80, unit:'books',    condition:'Excellent',  storage:'New York Warehouse', available:true,  projects:['Cartier NY Gala','Hermès NYC'],  notes:'Curated selection of art, fashion, photography, and architecture titles. Used for styling.',                                   dimensions:'Various',                purchaseYear:2023 },
  { id:'i20', name:'Black Pipe & Drape System (40 linear ft)',  category:'Décor',          qty:1,  unit:'system',   condition:'Good',       storage:'New York Warehouse', available:true,  projects:['Spotify SXSW','Nike Paris'],     notes:'40ft of adjustable upright pipe + drape. Black velvet drape panels. Good for backstage masking.',                              dimensions:'8–12ft adjustable',      purchaseYear:2022 },
  { id:'i21', name:'Flight Cases — AV Standard (×8)',           category:'Cases & Storage',qty:8,  unit:'cases',    condition:'Good',       storage:'New York Warehouse', available:false, projects:['Apple Dinner'],                  notes:'Standard AV transport cases. Out for Apple Dinner. Return Jul 17.',                                                            dimensions:'Various',                purchaseYear:2023 },
  { id:'i22', name:'Folding Tables — 6ft Banquet (×20)',        category:'Furniture',      qty:20, unit:'tables',   condition:'Fair',       storage:'New York Warehouse', available:true,  projects:['Spotify SXSW'],                  notes:'Production/back-of-house use only. Not client-facing. Some surface damage.',                                                  dimensions:'72" × 30"',              purchaseYear:2021 },
]
