/* CAPE Vendor Directory — sourced directly from Cape_Vendor_List CSVs. */
/* Do not hand-edit. Re-run the import script to update. */

export const VENDORS = [
{
  id: 'vc001',
  type: 'company',
  category: 'Cleaning',
  subcategory: '',
  name: 'Dream Clean',
  contactName: 'Alberto',
  website: 'https://www.dreamclean.space/',
  phone: '917-640-6794',
  email: '',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'The best cleaners in the world!',
  projects: []
},
{
  id: 'vc002',
  type: 'company',
  category: 'Content Capture',
  subcategory: 'Photo + Video',
  name: 'Mexicanografia',
  contactName: 'Andres Torres',
  website: 'https://mexicanografia.com/na',
  phone: '52 818-680-2442',
  email: '',
  city: 'Monterrey',
  state: 'NL',
  country: 'Mexico',
  costTier: '$',
  rating: '4 stars: They\'re good',
  producerNotes: '',
  projects: []
},
{
  id: 'vc003',
  type: 'company',
  category: 'Content Capture',
  subcategory: '',
  name: 'UNRVLD',
  contactName: 'Huy Nguyen',
  website: '',
  phone: '952-564-7928',
  email: 'madebyhuy@gmail.com',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc004',
  type: 'company',
  category: 'Fabrication',
  subcategory: 'Project fabrication, Airstream housing',
  name: 'Friendsxfamily (LA)',
  contactName: 'Brooke Little',
  website: '',
  phone: '347-820-0008',
  email: 'brooke@friendsxfamily.com',
  city: 'Los Angeles',
  state: 'CA',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc005',
  type: 'company',
  category: 'Fabrication',
  subcategory: 'Pajamas',
  name: 'Nikki',
  contactName: 'Claudia Dayan',
  website: 'https://maskki.mx/collections/pijamas',
  phone: '‪52 555-101-1010‬',
  email: '',
  city: 'Mexico City',
  state: 'Mexico City',
  country: 'Mexico',
  costTier: '$$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: '',
  projects: []
},
{
  id: 'vc006',
  type: 'company',
  category: 'Fabrication',
  subcategory: '',
  name: 'Duggal',
  contactName: 'Alex Hurst',
  website: 'https://duggal.com/',
  phone: '917-355-1134',
  email: 'alex.hurst@duggal.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'We have use Duggal for countless project as we have a very strong relationship with Alex',
  projects: []
},
{
  id: 'vc007',
  type: 'company',
  category: 'Fabrication',
  subcategory: '',
  name: '4x8 Workshop',
  contactName: 'John Powell',
  website: 'https://4x8workshop.com/',
  phone: '718-902-0046',
  email: 'John@4x8workshop.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Worked with them many times and they are a bit cheaper, but are usually busy and will need more lead time',
  projects: []
},
{
  id: 'vc008',
  type: 'company',
  category: 'Fabrication',
  subcategory: 'Signage/Neon',
  name: 'Vida Signs',
  contactName: '',
  website: 'https://vidasigns.com',
  phone: '',
  email: '',
  city: 'Manhattan',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: '',
  projects: []
},
{
  id: 'vc009',
  type: 'company',
  category: 'Food and Beverage',
  subcategory: '',
  name: 'Zoe Delue Catering',
  contactName: 'Zoe Delue',
  website: 'https://www.zoedeleu.com/',
  phone: '',
  email: '',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'One of the best and easiest to work with. Always beautiful food and David Byrne has even asked ot meet her at a previous event.',
  projects: []
},
{
  id: 'vc010',
  type: 'company',
  category: 'Food and Beverage',
  subcategory: '',
  name: 'Fluff + Fluff',
  contactName: 'Natalia',
  website: 'fluffandfluff.com',
  phone: '',
  email: '',
  city: '',
  state: '',
  country: '',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc011',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: '',
  name: 'Taylor Creative',
  contactName: 'Anika Aurelus',
  website: 'https://taylorcreativeinc.com/',
  phone: '',
  email: 'Anika@taylorcreativeinc.com',
  city: 'Queens',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Very clean furniture, the white couch was spotless',
  projects: []
},
{
  id: 'vc012',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: 'Plant / Florals',
  name: 'Holiday Foliage',
  contactName: 'Sweetie',
  website: 'holidayfoliagenyc.com',
  phone: '212-675-4300',
  email: 'holidayfoliage@aol.com',
  city: 'Manhattan',
  state: 'NY',
  country: 'USA',
  costTier: '$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Cheaper plant rental, but usually the pots that the plants come in are not the best quality',
  projects: []
},
{
  id: 'vc013',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: 'Florals',
  name: 'Joanna Block',
  contactName: 'Joanna Block',
  website: '',
  phone: '973-985-8654',
  email: 'joanna.block@gmail.com',
  city: 'Manhattan',
  state: 'NY',
  country: 'USA',
  costTier: '$$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'She\'s good and can do last minute arrangements, but a little too expensive for what we get sometimes.',
  projects: []
},
{
  id: 'vc014',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: 'Florals',
  name: 'Collective by Corey Hucko',
  contactName: 'Corey Hucko',
  website: 'https://www.instagram.com/______collective/?hl=en',
  phone: '',
  email: 'coreyhucko@gmail.com',
  city: 'New York',
  state: 'NY',
  country: 'USA',
  costTier: '$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'Beautiful florals for really really good price. Have worked with her for years now and she\'s always super reliable.',
  projects: []
},
{
  id: 'vc015',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: 'Arcade Game Rental vendor',
  name: '8 Bit Game Rental',
  contactName: 'Tom Trainor',
  website: '',
  phone: '602-579-1226',
  email: 'admin@8-bitrentals.com',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc016',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: 'Event furniture vendor',
  name: 'Pro Em (PHX)',
  contactName: 'Claire Donnigan(?)',
  website: '',
  phone: '248-227-7959',
  email: '',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc017',
  type: 'company',
  category: 'Furniture and Decor',
  subcategory: 'Florals',
  name: 'Special Event Designs',
  contactName: 'Aarica',
  website: '',
  phone: '480-430-1525',
  email: 'aarica@specialevent-designs.com',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc018',
  type: 'company',
  category: 'Lighting and AV',
  subcategory: 'Light Design/G&E/AV',
  name: 'Forza Studios (LA)',
  contactName: 'Nick Plotquin',
  website: '',
  phone: '310-430-0970',
  email: 'nick@forza.studio',
  city: 'Los Angeles',
  state: 'CA',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc019',
  type: 'company',
  category: 'Lighting and AV',
  subcategory: 'AV Tech (Screens + programming)',
  name: 'Forza Studios (LA)',
  contactName: 'Morgan Smith',
  website: '',
  phone: '310-621-5112',
  email: 'xfp101@gmail.com',
  city: 'Los Angeles',
  state: 'CA',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc020',
  type: 'company',
  category: 'Lighting and AV',
  subcategory: 'DJ/Speakers',
  name: 'Soundhouse',
  contactName: '',
  website: 'soundhousenyc.com',
  phone: '',
  email: 'rentals@soundhousenyc.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: '',
  projects: []
},
{
  id: 'vc021',
  type: 'company',
  category: 'Lighting and AV',
  subcategory: 'Light tech on site / Light Rental',
  name: 'Hotstrike Lighting',
  contactName: 'Mike Jones',
  website: '',
  phone: '213-361-6914',
  email: 'mike@hotstrikelighting.com',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc022',
  type: 'company',
  category: 'Logistics',
  subcategory: 'Local Production Company',
  name: 'E3',
  contactName: 'Teresa Montemayor',
  website: 'https://www.elementotres.com/new',
  phone: '‪52 811-183-2836‬',
  email: '',
  city: 'Monterrey',
  state: 'NL',
  country: 'Mexico',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: '',
  projects: []
},
{
  id: 'vc023',
  type: 'company',
  category: 'Logistics',
  subcategory: 'Moving',
  name: 'Imperial Movers',
  contactName: 'Mario',
  website: 'Imperialmovers.com',
  phone: '',
  email: 'Mario@imperialmovers.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Worked with them for years and they always provide a very professional crew',
  projects: []
},
{
  id: 'vc024',
  type: 'company',
  category: 'Merchandise',
  subcategory: 'Bandanas',
  name: 'Planet Apparel',
  contactName: 'Holly Trevino',
  website: 'https://planetapparel.com/',
  phone: '858-569-2090',
  email: 'holly@planetapparel.com',
  city: 'San Diego',
  state: 'CA',
  country: 'USA',
  costTier: '$$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'Known for their custom premium bandanas, but have pretty much anything you could possibly want customized. Super responsive and enthusiastic to help.',
  projects: []
},
{
  id: 'vc025',
  type: 'company',
  category: 'Merchandise',
  subcategory: 'Uniforms, stickers, divot tools',
  name: 'Promo Suns',
  contactName: 'Jessica Sun',
  website: 'https://www.promosuns.com/',
  phone: '631-513-6768',
  email: 'jessica@promosuns.com',
  city: 'New York',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'Have pretty much any kind of merch items, clothing, etc. that you could want customized. Super responsive and was willing to pick up the phone/text throughout the entire process. Was able to send out samples overnight for any request!',
  projects: []
},
{
  id: 'vc026',
  type: 'company',
  category: 'Merchandise',
  subcategory: 'Hat clip ball markers',
  name: 'Custom Made Golf Events',
  contactName: 'Kathleen',
  website: 'https://custommadegolfevents.com/?gad_source=1&gad_campaignid=21179597753&gbraid=0AAAAADiTSmsbUtGsJbRwVXw0uaDy7OHdl&gclid=CjwKCAiAncvMBhBEEiwA9GU_fihWtTJC_IUcG5VUavTWnnW4bzvvVQ53YSZVUBUVDkULseFANICPqBoCegoQAvD_BwE',
  phone: '973-650-3016',
  email: 'support@custommadegolfevents.com',
  city: 'Airmont',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Pretty much only makes custom golf merch and attire. Was super responsive so was great for last minute niche request.',
  projects: []
},
{
  id: 'vc027',
  type: 'company',
  category: 'Merchandise',
  subcategory: 'Light up wristbands',
  name: 'Pixmob',
  contactName: 'Alexis Daudelin',
  website: 'https://pixmob.com/',
  phone: '',
  email: 'ada@pixmob.com',
  city: 'Montreal',
  state: 'Quebec',
  country: 'Canada',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'We didn\'t proceed with the light up wristbands for this project, but was surprisingly more affordable than expected. Would be great to work with them in the future.',
  projects: []
},
{
  id: 'vc028',
  type: 'company',
  category: 'Printer',
  subcategory: '',
  name: 'Alpha Graphics',
  contactName: 'Rondelyn',
  website: '',
  phone: '480-991-1636',
  email: 'airpark@alphagraphics.com',
  city: 'Scottsdale',
  state: 'AZ',
  country: 'USA',
  costTier: '$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: '',
  projects: []
},
{
  id: 'vc029',
  type: 'company',
  category: 'Staffing',
  subcategory: 'Local Public Relations',
  name: 'Maria Jose Gutierrez',
  contactName: 'Maria Jose Gutierrez',
  website: '',
  phone: '52 811-917-2855',
  email: '',
  city: 'Monterrey',
  state: 'NL',
  country: 'Mexico',
  costTier: '$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: '',
  projects: []
},
{
  id: 'vc030',
  type: 'company',
  category: 'Staffing',
  subcategory: 'Bar staffing',
  name: 'M Catering',
  contactName: 'Lauren Bircher',
  website: '',
  phone: '480-490-3829',
  email: 'laurenb@mculinary.com',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc031',
  type: 'company',
  category: 'Staffing',
  subcategory: 'Brand Ambassadors',
  name: 'Brand Besties',
  contactName: 'Ben Bon',
  website: '',
  phone: '520-343-1941',
  email: 'benbon@brandbesties.com',
  city: '',
  state: '',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc032',
  type: 'company',
  category: '',
  subcategory: 'Event design',
  name: 'Up Your Aly Events (PHX)',
  contactName: 'Aly',
  website: '',
  phone: '916-804-9230',
  email: 'alyson@upyouralyevents.com',
  city: 'Phoenix',
  state: 'AZ',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vc033',
  type: 'company',
  category: '',
  subcategory: 'Event design',
  name: 'Up Your Aly Events (PHX)',
  contactName: 'Lexi',
  website: '',
  phone: '916-804-9230',
  email: 'lexi@upyouralyevents.com',
  city: 'Phoenix',
  state: 'AZ',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vf001',
  type: 'freelancer',
  category: 'Photographer',
  subcategory: '',
  name: 'Matt Genovese',
  contactName: 'Matt',
  website: 'https://mattgenovese.com',
  phone: '973-897-8078',
  email: 'mattgenovesephoto@gmail.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Josh has known Matt for over 15 years and we have worked with him for years',
  projects: []
},
{
  id: 'vf002',
  type: 'freelancer',
  category: 'Videographer',
  subcategory: '',
  name: 'Mike Klubek',
  contactName: 'Mike',
  website: 'https://www.mikeklubeck.com/',
  phone: '732-609-4054',
  email: 'mikeklubeck@gmail.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$',
  rating: '4 stars: They\'re good',
  producerNotes: 'Close friend of Nathalie and we have worked with him for years',
  projects: []
},
{
  id: 'vf003',
  type: 'freelancer',
  category: 'Videographer',
  subcategory: '',
  name: 'Jp Blair',
  contactName: 'Jp',
  website: 'https://www.jonathanphillipblair.com/',
  phone: '973-600-4023',
  email: 'jonathanphillipblair@gmail.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '$$$',
  rating: '5 stars: Exceptional. We love them!',
  producerNotes: 'Old friend will be a bit more expensive but worth it',
  projects: []
},
{
  id: 'vf004',
  type: 'freelancer',
  category: 'Photographer',
  subcategory: '',
  name: 'Devon Corman',
  contactName: 'Devon',
  website: 'https://www.devoncorman.com/',
  phone: '',
  email: 'devonolivercorman@gmail.com',
  city: 'Brooklyn',
  state: 'NY',
  country: 'USA',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
{
  id: 'vf005',
  type: 'freelancer',
  category: 'Video Editor',
  subcategory: '',
  name: 'Cuong Ngo',
  contactName: 'CN',
  website: 'www.cuongdngo.com',
  phone: '',
  email: 'cngo86@gmail.com',
  city: '',
  state: '',
  country: '',
  costTier: '',
  rating: '',
  producerNotes: '',
  projects: []
},
]

export const ALL_CATEGORIES = ["Cleaning", "Content Capture", "Fabrication", "Food and Beverage", "Furniture and Decor", "Lighting and AV", "Logistics", "Merchandise", "Photographer", "Printer", "Staffing", "Video Editor", "Videographer"]
export const ALL_COST_TIERS = ["$", "$$", "$$$", "$$$$"]

export const COMPANY_CATS   = [...new Set(VENDORS.filter(v=>v.type==='company').map(v=>v.category).filter(Boolean))].sort()
export const FREELANCER_CATS = [...new Set(VENDORS.filter(v=>v.type==='freelancer').map(v=>v.category).filter(Boolean))].sort()