export const EXISTING_PRODUCTIONS = [
  {
    id: 'p1',
    name: 'Nike House of Innovation — Paris Pop-Up',
    client: 'Nike',
    type: 'Retail Takeover',
    location: 'Paris, France',
    eventDate: 'Aug 12, 2026',
    daysOut: 46,
    status: 'on-schedule',
    statusLabel: 'On schedule',
    phase: 'Fabrication',
    lead: '',
    ep: '',
    nextGate: 'Install review · Jul 28',
  },
  {
    id: 'p2',
    name: 'Spotify Loud & Clear — SXSW Activation',
    client: 'Spotify',
    type: 'Brand Activation',
    location: 'Austin, TX',
    eventDate: 'Mar 14, 2027',
    daysOut: 260,
    status: 'attention',
    statusLabel: 'Fabrication review needed',
    phase: 'Pre-production',
    lead: '',
    ep: '',
    nextGate: 'Creative lock · Jul 18',
  },
  {
    id: 'p3',
    name: 'Loewe Crafted World — Miami Design Week',
    client: 'Loewe',
    type: 'Experiential',
    location: 'Miami, FL',
    eventDate: 'Dec 2, 2026',
    daysOut: 158,
    status: 'pre',
    statusLabel: 'Pre-production',
    phase: 'Creative Development',
    lead: '',
    ep: '',
    nextGate: 'Vendor awards · Aug 5',
  },
]

export const TEAM_MEMBERS = [
  ,
  ,
  ,
  ,
  ,
  ,
]

export const DEFAULT_PRODUCTION = {
  name: 'Apple Vision Pro Executive Dinner',
  client: 'Apple',
  type: 'Executive Dinner / Brand Experience',
  location: 'Brooklyn, NY',
  venue: 'Brooklyn Tower, 73rd Floor',
  budgetTier: 'Flagship',
  budgetRange: '$1.2M',
  guestCount: '120 guests',
  eventDate: 'July 16, 2026',
  eventDateShort: 'Jul 16',
  eventYear: '2026',
  daysOut: 20,
  currentPhase: 'Final production',
  ep: '',
  epInitials: 'RC',
  lead: '',
  leadInitials: 'MO',
}

export const WORKSTREAMS = [
  {
    id: 'creative',
    name: 'Creative',
    owner: '',
    ownerInitials: '',
    ownerColor: 'green',
    nextDeliverable: 'Environmental graphics spec',
    nextDate: 'Jul 1',
    status: 'on-track',
    statusLabel: 'On track',
    completedTasks: 3,
    taskCount: 6,
    deliverables: [
      'Concept presentation & creative deck',
      'Environmental design direction',
      'Spatial layout and flow plan',
      'Brand asset delivery & final art approval',
      'Environmental graphics specification',
      'Presentation rehearsal run-through',
    ],
  },
  {
    id: 'production',
    name: 'Production',
    owner: '',
    ownerInitials: '',
    ownerColor: 'blue',
    nextDeliverable: 'Master run-of-show',
    nextDate: 'Jul 3',
    status: 'on-track',
    statusLabel: 'On track',
    completedTasks: 2,
    taskCount: 8,
    deliverables: [
      'Master production schedule',
      'Vendor coordination & call sheets',
      'Site survey report & access plan',
      'Run-of-show & event-day timeline',
      'Crew briefing documents',
      'Post-event wrap report',
      'Debrief & lessons-learned summary',
      'Final vendor reconciliation',
    ],
  },
  {
    id: 'hospitality',
    name: 'Hospitality',
    owner: '',
    ownerInitials: '',
    ownerColor: 'amber',
    nextDeliverable: 'Confirmed guest list',
    nextDate: 'Jun 30',
    status: 'attention',
    statusLabel: 'Guest list pending',
    completedTasks: 1,
    taskCount: 7,
    deliverables: [
      'Guest list management & RSVPs',
      'Catering brief & menu approval',
      'Wine and beverage selection',
      'Seating plan & table assignments',
      'VIP arrival & escort protocol',
      'Dietary requirements & allergy matrix',
      'Evening-of hospitality run-of-show',
    ],
  },
  {
    id: 'fabrication',
    name: 'Fabrication',
    owner: '',
    ownerInitials: '',
    ownerColor: 'blue',
    nextDeliverable: 'Build schedule confirmation',
    nextDate: 'Jul 2',
    status: 'on-track',
    statusLabel: 'On track',
    completedTasks: 4,
    taskCount: 7,
    deliverables: [
      'Vendor RFQ & award recommendation',
      'Material specification sheet',
      'Structural engineering sign-off',
      'Build schedule & QC milestones',
      'Install supervision brief',
      'Strike and removal plan',
      'Final QC walkthrough sign-off',
    ],
  },
  {
    id: 'logistics',
    name: 'Logistics',
    owner: '',
    ownerInitials: '',
    ownerColor: 'blue',
    nextDeliverable: 'Load-in schedule',
    nextDate: 'Jul 8',
    status: 'on-track',
    statusLabel: 'On track',
    completedTasks: 3,
    taskCount: 5,
    deliverables: [
      'Venue agreement & access schedule',
      'Permits, insurance & COI',
      'Freight & delivery coordination',
      'Load-in & load-out schedule',
      'Security & venue liaison brief',
    ],
  },
  {
    id: 'content',
    name: 'Content Capture',
    owner: '',
    ownerInitials: '',
    ownerColor: 'green',
    nextDeliverable: 'Shot list approval',
    nextDate: 'Jul 5',
    status: 'on-track',
    statusLabel: 'On track',
    completedTasks: 1,
    taskCount: 4,
    deliverables: [
      'Photography & video brief',
      'Shot list & coverage plan',
      'Post-production delivery schedule',
      'Asset usage rights confirmation',
    ],
  },
]

export const MILESTONES = [
  { label: 'Kickoff',        date: 'Jun 26', sublabel: 'Today',    done: true,  isEvent: false, isNext: false },
  { label: 'Creative lock',  date: 'Jul 1',  sublabel: '5 days',   done: false, isEvent: false, isNext: true  },
  { label: 'Client approval',date: 'Jul 3',  sublabel: '7 days',   done: false, isEvent: false, isNext: false },
  { label: 'Vendor awards',  date: 'Jul 7',  sublabel: '11 days',  done: false, isEvent: false, isNext: false },
  { label: 'Fab start',      date: 'Jul 9',  sublabel: '13 days',  done: false, isEvent: false, isNext: false },
  { label: 'Site survey',    date: 'Jul 13', sublabel: '17 days',  done: false, isEvent: false, isNext: false },
  { label: 'Load-in',        date: 'Jul 15', sublabel: '19 days',  done: false, isEvent: false, isNext: false },
  { label: 'Dinner',         date: 'Jul 16', sublabel: 'Event day',done: false, isEvent: true,  isNext: false },
]

export const DAY1_ACTIONS = [
  { id: 'd1', text: 'Upload awarded brief and creative concept reference', owner: '',      ownerInitials: '', ownerColor: 'green', urgent: true  },
  { id: 'd2', text: 'Confirm Brooklyn Tower venue hold in writing',         owner: '',     ownerInitials: '', ownerColor: 'blue',  urgent: true  },
  { id: 'd3', text: 'Schedule all-hands production kickoff call',           owner: '',   ownerInitials: '', ownerColor: 'amber', urgent: false },
  { id: 'd4', text: 'Issue fabrication RFQ to preferred vendor shortlist',  owner: '',ownerInitials: '', ownerColor: 'blue',  urgent: false },
  { id: 'd5', text: 'Send Apple client team production summary',            owner: '',   ownerInitials: '', ownerColor: 'amber', urgent: false },
  { id: 'd6', text: 'Begin guest list collection and RSVP outreach',        owner: '',  ownerInitials: '', ownerColor: 'amber', urgent: false },
]

export const GENERATION_STEPS = [
  { label: 'Creating workstreams',        sub: 'Applying Flagship executive dinner methodology — Creative, Production, Hospitality, Fabrication, Logistics, Content' },
  { label: 'Assigning department leads',  sub: 'Mapping your team to workstream ownership based on roles' },
  { label: 'Building milestone timeline', sub: 'Calculating production gates backward from July 16' },
  { label: 'Preparing Day 1 action plan', sub: 'Identifying first-48-hour priorities across all department leads' },
  { label: 'Organizing production brief', sub: 'Structuring deliverables, checklists, and handoffs per workstream' },
  { label: 'Production ready',            sub: '' },
]
